//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsAndTravels.Prism.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripsAndTravels.Prism.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new trip.
        /// </summary>
        public static string AddNewTrip {
            get {
                return ResourceManager.GetString("AddNewTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Id.
        /// </summary>
        public static string CheckIdTrip {
            get {
                return ResourceManager.GetString("CheckIdTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the internet connection..
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a document..
        /// </summary>
        public static string DocumentError {
            get {
                return ResourceManager.GetString("DocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your document number....
        /// </summary>
        public static string DocumentPlaceHolder {
            get {
                return ResourceManager.GetString("DocumentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email..
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDateTrip {
            get {
                return ResourceManager.GetString("EndDateTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name..
        /// </summary>
        public static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name....
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Trip.
        /// </summary>
        public static string IdTrip {
            get {
                return ResourceManager.GetString("IdTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Id Trip..
        /// </summary>
        public static string IdTripError1 {
            get {
                return ResourceManager.GetString("IdTripError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id Trip must start with three letters indicating the city and end with three numbers indicating the number of trip..
        /// </summary>
        public static string IdTripError2 {
            get {
                return ResourceManager.GetString("IdTripError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id Trip....
        /// </summary>
        public static string IdTripPlaceHolder {
            get {
                return ResourceManager.GetString("IdTripPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name..
        /// </summary>
        public static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name....
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password incorrect.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user.
        /// </summary>
        public static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm..
        /// </summary>
        public static string PasswordConfirmError1 {
            get {
                return ResourceManager.GetString("PasswordConfirmError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match..
        /// </summary>
        public static string PasswordConfirmError2 {
            get {
                return ResourceManager.GetString("PasswordConfirmError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirm....
        /// </summary>
        public static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone....
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone..
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as.
        /// </summary>
        public static string RegisterAs {
            get {
                return ResourceManager.GetString("RegisterAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a role..
        /// </summary>
        public static string RegisterAsError {
            get {
                return ResourceManager.GetString("RegisterAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a role....
        /// </summary>
        public static string RegisterAsPlaceHolder {
            get {
                return ResourceManager.GetString("RegisterAsPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See trip details.
        /// </summary>
        public static string SeeTripDetails {
            get {
                return ResourceManager.GetString("SeeTripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StarDateTrip {
            get {
                return ResourceManager.GetString("StarDateTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Details.
        /// </summary>
        public static string TripDetails {
            get {
                return ResourceManager.GetString("TripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
